python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt


