python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_la_RR_MK.txt


