python "schedule_basico_G&T_V15.py" .\Inst\la01.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la02.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la03.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la04.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la05.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la06.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la07.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la08.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la09.txt SPT MK >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la10.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la11.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la12.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la13.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la14.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la15.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la16.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la17.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la18.txt SPT MK >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la19.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la20.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la21.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la22.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la23.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la24.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la25.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la26.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la27.txt SPT MK >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la28.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la29.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la30.txt SPT MK >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la31.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la32.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la33.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la34.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la35.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la36.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la37.txt SPT MK >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la38.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la39.txt SPT MK  >> .\Res\sal_la_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\la40.txt SPT MK >> .\Res\sal_la_SPT_MK.txt