python "schedule_basico_G&T_V15.py" .\Inst\swv01.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv02.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv03.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv04.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv05.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv06.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv07.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv08.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv09.txt SPT MK >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv10.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv11.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swV12.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swV13.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swV14.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv15.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv16.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv17.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv18.txt SPT MK >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv19.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\swv20.txt SPT MK  >> .\Res\sal_swv_SPT_MK.txt