python "Scheduler.py" .\Instances\la01.txt RR MK  > .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la02.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la03.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la04.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la05.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la06.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la07.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la08.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la09.txt RR MK >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la10.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la11.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la12.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la13.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la14.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la15.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la16.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la17.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la18.txt RR MK >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la19.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la20.txt RR MK  >> .\Res\sal_UB_la_RR_MK.txt
python "Scheduler.py" .\Instances\la01.txt SPT MK  > .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la02.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la03.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la04.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la05.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la06.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la07.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la08.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la09.txt SPT MK >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la10.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la11.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la12.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la13.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la14.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la15.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la16.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la17.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la18.txt SPT MK >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la19.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt
python "Scheduler.py" .\Instances\la20.txt SPT MK  >> .\Res\sal_UB_la_SPT_MK.txt


