python "schedule_basico_G&T_V15.py" .\Inst\ta01.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta02.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta03.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta04.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta05.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta06.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta07.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta08.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta09.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta10.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta11.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta12.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta13.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta14.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta15.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta16.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta17.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta18.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta19.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta20.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta21.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta22.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta23.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta24.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta25.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta26.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta27.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta28.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta29.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta30.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta31.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta32.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta33.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta34.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta35.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta36.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta37.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta38.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta39.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta40.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta41.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta42.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta43.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta44.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta45.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta46.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta47.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta48.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta49.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta50.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta51.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta52.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta53.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta54.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta55.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta56.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta57.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta58.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta59.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta60.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta61.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta62.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta63.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta64.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta65.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta66.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta67.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta68.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta69.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta70.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta71.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta72.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta73.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta74.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta75.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta76.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta77.txt SPT MK >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta78.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta79.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt
python "schedule_basico_G&T_V15.py" .\Inst\ta80.txt SPT MK  >> .\Res\sal_ta_SPT_MK.txt